### ISSUE TITLE
Provide some measures against 7-day history, not just 24h

### ISSUE THREAD

**Issue by DamonHD** [DamonHD/reutils#1]
In particular peak demands make more sense over a weekly period.

24h measures still have some value, ie identifying best and worst times for loads that cannot be delayed more than 24h.

Will require keeping state.

**Comment by DominicMcCann** [comment]
To add further to the complexity; a good compromise might be a reference based on a 50/50% mix of the 24h and the 7day averages.

**Comment by DamonHD** [comment]
Thanks!

Why 50/50%?  And note that I barely do averages anywhere, I think that top x% and bottom x% are more robust and informative generally.

**Comment by DominicMcCann** [comment]
50/50% mix - just for "simplicity / the need to plump for something". Yes you could use top x% and bottom x% for both 24h and 7day data sets and then mix in this way. Just a suggestion - any single method is a compromise.

**Comment by DamonHD** [comment]
(Note: create a parallel set of '7-day' flags, eg to drive powermgr without disturbing other uses.)

**Comment by DamonHD** [comment]
Thoughts as of this morning:

  * Base on contents of logs (comparing to effective consumer intensity)
  * Compute/publish 168h intensity colour (including R and SG signals)
  * Sample hours unbiased, initially 1st in hr.  (Mean would be G-weighted.)

**Comment by DominicMcCann** [comment]
Hi Damon
I am not sure I understand what is meant by 168h intensity colour?
Nor what the R and SG signals refer to?
Does this link to some GitHub code?
Best
Dom

________________________________

**Comment by DamonHD** [comment]
Hi,

These were my cryptic 4am notes to myself.

1) I'm now writing logs with the intensity in every 5 or 10 minutes.

See https://www.earth.org.uk/data/FUELINST/log/live/ 

One off-putting element of the work before would have been managing the storage for a rolling 7 days' data.  Reading back from those logs is not ideal in terms of efficiency, but will do.

Those logs store the effective intensity as seen by the consumer, rather at generation, so I need to remember to compare with that to compute a Red / Amber / Green score.

2) 168h was my way of saying rolling-seven-day and not necessarily starting at midnight on the first of those days.  Eg if it's 4pm now then the window should likely start from 4pm 7 days ago.  R is red and SG is super-green (green and with no storage discharging) as those are currently the key items I use.

No code yet, just capturing how I suddenly thought (in the middle of the night) that I should probably do it...

Rgds

Damon

**Comment by DamonHD** [comment]
V1.1.17 now computes a (up to) 7-day view alongside the 24h view.

It makes a quiet note at the top of the HTML page if the status colour for 7d is not the same as for 24h.

7d versions of the green/supergreen/red flag are now maintained.

I shall be using them myself cautiously for a bit before banging the drum about them!

**Comment by DominicMcCann** [comment]
Where is the 7day average flag displayed?
Dom
________________________________
