### ISSUE TITLE
I'd like to see the actual figure in the tweet e.g. 123gCO2/kWh now.

### ISSUE THREAD

**Issue by GeoffBeacon** [DamonHD/reutils#3]

**Comment by DamonHD** [comment]
End-user or generation?

Note: I am not (yet) folding in any generation that doesn't enter the high-voltage network, so most solar and a fair chunk of wind...

**Comment by GeoffBeacon** [comment]
End-user is OK.

**Comment by DamonHD** [comment]
OK.

I don't have much coding time right now.  A PR would make this happen much sooner!  B^>

**Comment by DamonHD** [comment]
OK, after a very slight delay (!) I'm hoping to make some progress on this today!  %-P

See also: https://twitter.com/AbigailDombey/status/1457278820495527940

Rgds

Damon

**Comment by DamonHD** [comment]
In theory, this is now done!

**Comment by DamonHD** [comment]
See https://twitter.com/EarthOrgUK/status/1457317999791288325

> National Grid CO2 intensity 106gCO2/kWh is average so don't run big appliances now if you can wait. http://bit.ly/3usoe #CO2 |1204
